spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:cyberstar;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always


logging:
  level:
    ron: info
