insert into "cyberstar" ("login_id", "name") values('Ron000', 'Test000'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron000'; 
insert into "cyberstar" ("login_id", "name") values('Ron001', 'Test001'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron001'; 
insert into "cyberstar" ("login_id", "name") values('Ron002', 'Test002'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron002'; 
insert into "cyberstar" ("login_id", "name") values('Ron003', 'Test003'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron003'; 
insert into "cyberstar" ("login_id", "name") values('Ron004', 'Test004'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron004'; 
insert into "cyberstar" ("login_id", "name") values('Ron005', 'Test005'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron005'; 
insert into "cyberstar" ("login_id", "name") values('Ron006', 'Test006'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron006'; 
insert into "cyberstar" ("login_id", "name") values('Ron007', 'Test007'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron007'; 
insert into "cyberstar" ("login_id", "name") values('Ron008', 'Test008'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron008'; 
insert into "cyberstar" ("login_id", "name") values('Ron009', 'Test009'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron009'; 
insert into "cyberstar" ("login_id", "name") values('Ron010', 'Test010'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron010'; 
insert into "cyberstar" ("login_id", "name") values('Ron011', 'Test011'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron011'; 
insert into "cyberstar" ("login_id", "name") values('Ron012', 'Test012'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron012'; 
insert into "cyberstar" ("login_id", "name") values('Ron013', 'Test013'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron013'; 
insert into "cyberstar" ("login_id", "name") values('Ron014', 'Test014'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron014'; 
insert into "cyberstar" ("login_id", "name") values('Ron015', 'Test015'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron015'; 
insert into "cyberstar" ("login_id", "name") values('Ron016', 'Test016'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron016'; 
insert into "cyberstar" ("login_id", "name") values('Ron017', 'Test017'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron017'; 
insert into "cyberstar" ("login_id", "name") values('Ron018', 'Test018'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron018'; 
insert into "cyberstar" ("login_id", "name") values('Ron019', 'Test019'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron019'; 
insert into "cyberstar" ("login_id", "name") values('Ron020', 'Test020'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron020'; 
insert into "cyberstar" ("login_id", "name") values('Ron021', 'Test021'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron021'; 
insert into "cyberstar" ("login_id", "name") values('Ron022', 'Test022'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron022'; 
insert into "cyberstar" ("login_id", "name") values('Ron023', 'Test023'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron023'; 
insert into "cyberstar" ("login_id", "name") values('Ron024', 'Test024'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron024'; 
insert into "cyberstar" ("login_id", "name") values('Ron025', 'Test025'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron025'; 
insert into "cyberstar" ("login_id", "name") values('Ron026', 'Test026'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron026'; 
insert into "cyberstar" ("login_id", "name") values('Ron027', 'Test027'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron027'; 
insert into "cyberstar" ("login_id", "name") values('Ron028', 'Test028'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron028'; 
insert into "cyberstar" ("login_id", "name") values('Ron029', 'Test029'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron029'; 
insert into "cyberstar" ("login_id", "name") values('Ron030', 'Test030'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron030'; 
insert into "cyberstar" ("login_id", "name") values('Ron031', 'Test031'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron031'; 
insert into "cyberstar" ("login_id", "name") values('Ron032', 'Test032'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron032'; 
insert into "cyberstar" ("login_id", "name") values('Ron033', 'Test033'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron033'; 
insert into "cyberstar" ("login_id", "name") values('Ron034', 'Test034'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron034'; 
insert into "cyberstar" ("login_id", "name") values('Ron035', 'Test035'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron035'; 
insert into "cyberstar" ("login_id", "name") values('Ron036', 'Test036'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron036'; 
insert into "cyberstar" ("login_id", "name") values('Ron037', 'Test037'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron037'; 
insert into "cyberstar" ("login_id", "name") values('Ron038', 'Test038'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron038'; 
insert into "cyberstar" ("login_id", "name") values('Ron039', 'Test039'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron039'; 
insert into "cyberstar" ("login_id", "name") values('Ron040', 'Test040'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron040'; 
insert into "cyberstar" ("login_id", "name") values('Ron041', 'Test041'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron041'; 
insert into "cyberstar" ("login_id", "name") values('Ron042', 'Test042'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron042'; 
insert into "cyberstar" ("login_id", "name") values('Ron043', 'Test043'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron043'; 
insert into "cyberstar" ("login_id", "name") values('Ron044', 'Test044'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron044'; 
insert into "cyberstar" ("login_id", "name") values('Ron045', 'Test045'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron045'; 
insert into "cyberstar" ("login_id", "name") values('Ron046', 'Test046'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron046'; 
insert into "cyberstar" ("login_id", "name") values('Ron047', 'Test047'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron047'; 
insert into "cyberstar" ("login_id", "name") values('Ron048', 'Test048'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron048'; 
insert into "cyberstar" ("login_id", "name") values('Ron049', 'Test049'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron049'; 
insert into "cyberstar" ("login_id", "name") values('Ron050', 'Test050'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron050'; 
insert into "cyberstar" ("login_id", "name") values('Ron051', 'Test051'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron051'; 
insert into "cyberstar" ("login_id", "name") values('Ron052', 'Test052'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron052'; 
insert into "cyberstar" ("login_id", "name") values('Ron053', 'Test053'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron053'; 
insert into "cyberstar" ("login_id", "name") values('Ron054', 'Test054'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron054'; 
insert into "cyberstar" ("login_id", "name") values('Ron055', 'Test055'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron055'; 
insert into "cyberstar" ("login_id", "name") values('Ron056', 'Test056'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron056'; 
insert into "cyberstar" ("login_id", "name") values('Ron057', 'Test057'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron057'; 
insert into "cyberstar" ("login_id", "name") values('Ron058', 'Test058'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron058'; 
insert into "cyberstar" ("login_id", "name") values('Ron059', 'Test059'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron059'; 
insert into "cyberstar" ("login_id", "name") values('Ron060', 'Test060'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron060'; 
insert into "cyberstar" ("login_id", "name") values('Ron061', 'Test061'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron061'; 
insert into "cyberstar" ("login_id", "name") values('Ron062', 'Test062'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron062'; 
insert into "cyberstar" ("login_id", "name") values('Ron063', 'Test063'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron063'; 
insert into "cyberstar" ("login_id", "name") values('Ron064', 'Test064'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron064'; 
insert into "cyberstar" ("login_id", "name") values('Ron065', 'Test065'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron065'; 
insert into "cyberstar" ("login_id", "name") values('Ron066', 'Test066'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron066'; 
insert into "cyberstar" ("login_id", "name") values('Ron067', 'Test067'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron067'; 
insert into "cyberstar" ("login_id", "name") values('Ron068', 'Test068'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron068'; 
insert into "cyberstar" ("login_id", "name") values('Ron069', 'Test069'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron069'; 
insert into "cyberstar" ("login_id", "name") values('Ron070', 'Test070'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron070'; 
insert into "cyberstar" ("login_id", "name") values('Ron071', 'Test071'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron071'; 
insert into "cyberstar" ("login_id", "name") values('Ron072', 'Test072'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron072'; 
insert into "cyberstar" ("login_id", "name") values('Ron073', 'Test073'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron073'; 
insert into "cyberstar" ("login_id", "name") values('Ron074', 'Test074'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron074'; 
insert into "cyberstar" ("login_id", "name") values('Ron075', 'Test075'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron075'; 
insert into "cyberstar" ("login_id", "name") values('Ron076', 'Test076'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron076'; 
insert into "cyberstar" ("login_id", "name") values('Ron077', 'Test077'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron077'; 
insert into "cyberstar" ("login_id", "name") values('Ron078', 'Test078'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron078'; 
insert into "cyberstar" ("login_id", "name") values('Ron079', 'Test079'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron079'; 
insert into "cyberstar" ("login_id", "name") values('Ron080', 'Test080'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron080'; 
insert into "cyberstar" ("login_id", "name") values('Ron081', 'Test081'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron081'; 
insert into "cyberstar" ("login_id", "name") values('Ron082', 'Test082'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron082'; 
insert into "cyberstar" ("login_id", "name") values('Ron083', 'Test083'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron083'; 
insert into "cyberstar" ("login_id", "name") values('Ron084', 'Test084'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron084'; 
insert into "cyberstar" ("login_id", "name") values('Ron085', 'Test085'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron085'; 
insert into "cyberstar" ("login_id", "name") values('Ron086', 'Test086'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron086'; 
insert into "cyberstar" ("login_id", "name") values('Ron087', 'Test087'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron087'; 
insert into "cyberstar" ("login_id", "name") values('Ron088', 'Test088'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron088'; 
insert into "cyberstar" ("login_id", "name") values('Ron089', 'Test089'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron089'; 
insert into "cyberstar" ("login_id", "name") values('Ron090', 'Test090'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron090'; 
insert into "cyberstar" ("login_id", "name") values('Ron091', 'Test091'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron091'; 
insert into "cyberstar" ("login_id", "name") values('Ron092', 'Test092'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron092'; 
insert into "cyberstar" ("login_id", "name") values('Ron093', 'Test093'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron093'; 
insert into "cyberstar" ("login_id", "name") values('Ron094', 'Test094'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron094'; 
insert into "cyberstar" ("login_id", "name") values('Ron095', 'Test095'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron095'; 
insert into "cyberstar" ("login_id", "name") values('Ron096', 'Test096'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron096'; 
insert into "cyberstar" ("login_id", "name") values('Ron097', 'Test097'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron097'; 
insert into "cyberstar" ("login_id", "name") values('Ron098', 'Test098'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron098'; 
insert into "cyberstar" ("login_id", "name") values('Ron099', 'Test099'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron099'; 
insert into "cyberstar" ("login_id", "name") values('Ron100', 'Test100'); 
insert into "relationship" ("cyberstar_id") select "cyberstar_id" from "cyberstar" where login_id = 'Ron100'; 
